[project]
name = "nova"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "manim>=0.19.0",
    "mcp[cli,server]>=1.14.1",
]
